### ISSUE TITLE
Running flye assemblies and getting error wanting contigs.paths file for spades

### ISSUE THREAD

**Issue by emilyjunkins** [metagentools/GraphBin#46]
Hello,

I am running graphbin v 1.7.1 and python version 3.10.13

First, I was unable to get the python support scripts to work so I renamed all of my files to make naming consistent and made the csv file with custom scripts. 

When I tried to run the following code:

`graphbin --contigs /home/ejunkins/LS01_hifi_coveragebin/LS01_001_assembly_renamed_edges.fasta --binned /home/ejunkins/LS01_hifi_coveragebin/bins/001/contignames/edges/LS01_001_all_edges_graphbin.csv --graph /home/ejunkins/jgi_assemblygraphs/NGXTG/flye/assembly_graph.gfa --output /home/ejunkins/LS01_hifi_coveragebin/bins/001/graphbin_out --prefix graphbin_metabat2_LS01_001_bin_with_cov --assembler flye`

I get this error:
`2024-02-12 12:28:23,452 - ERROR - Please make sure to provide the path to the contigs.paths file.
2024-02-12 12:28:23,453 - INFO - Exiting GraphBin... Bye...!`

My understanding was that this was only for spades assemblies...

**Comment by Vini2** [comment]
Hello @emilyjunkins,

So sorry for getting back to you late.

GraphBin now supports the original contigs produced from Flye. The [example command](https://graphbin.readthedocs.io/en/latest/usage/) would look something like this.

```
graphbin --assembler flye --graph assembly_graph.gfa --contigs assembly.fasta --paths assembly_info.txt--binned binning_result.csv --output graphbin_out
```
The path option is required for both SPAdes and Flye assemblies as they produce a unitig graph instead of a contig graph.

Hope this clears things.

**Comment by Vini2** [comment]
Closing this issue. Please re-open if needed.
